### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by craipe** [CNflysky/TC358870#1]
Hi friend. Can I ask you to share a project? I want to create a tablet on CM 4, but I can't find the correct circuit and trace of this board anywhere on the Internet, I found only Gerber files from you. I would be very grateful for your help. I can pay if required. If it doesn't bother you, export the project to Easy E DA PRO so that I can install it for myself.

嗨，朋友。 我可以请你分享一个项目吗? 我想在CM4上创建一个平板电脑，但我在互联网上的任何地方都找不到这个板的正确电路和痕迹，我只从你那里找到了Gerber文件。 我将非常感谢你的帮助。 如果需要，我可以付钱。 如果它不打扰您，请将项目导出到EasyEDA PRO，以便我可以自己安装它。

**Comment by CNflysky** [comment]
> 

CM4 has 2 MIPI DSI hosts so you can directly connect them to your DSI display. no need for use this bridge chip.

**Comment by CNflysky** [comment]
closed as no more replies
