### ISSUE TITLE
Orientation and Display Compatibility - Question

### ISSUE THREAD

**Issue by pushpinderv** [CNflysky/TC358870#3]
What is the default orientation of the screen when used with this board - Portrait or Landscape?

Can it be controlled on the connected device, say Raspberry Pi 4 (I want to use display in landscape mode)?

Will the board support Wisecoco 7 inch display - https://www.aliexpress.com/item/1005004877724262.html (Innolux P068HFB-DK1) without any hardware changes? (I have display datasheet with signal and timing details)

EDIT:
Can you also please provide the pcb files for EasyEDA for open source customizations? I need to integrate this board into a personal project, and might need to change the hdmi connector to an fpc connector instead. I can also contribute my updates to your project once I manage to get my panel working.

**Comment by CNflysky** [comment]
> What is the default orientation of the screen when used with this board - Portrait or Landscape?
> 
> Can it be controlled on the connected device, say Raspberry Pi 4 (I want to use display in landscape mode)?
> 
> Will the board support Wisecoco 7 inch display - https://www.aliexpress.com/item/1005004877724262.html (Innolux P068HFB-DK1) without any hardware changes? (I have display datasheet with signal and timing details)
> 
> EDIT: Can you also please provide the pcb files for EasyEDA for open source customizations? I need to integrate this board into a personal project, and might need to change the hdmi connector to an fpc connector instead. I can also contribute my updates to your project once I manage to get my panel working.

1. it depends on your panel's display mode,the chip itself can't change panel's rotation, you can look at the resolution on your panel's datasheet -- e.g. 1920 * 1080 means landscape, 1080 * 1920 means portrait.
2. you can design a adapter board, which adapts the fpc connector on the board to your panel's.
3. pcb source files currently can not be exported. i'll upload it when i fix it.

**Comment by pushpinderv** [comment]
Thanks a lot for your response, and keeping this project active!
Looking forward for the pcb source files!

Closing this for now.

**Comment by CNflysky** [comment]
Bad news: The schematic file is corrupted and cannot be exported. However, I have managed to export the PCB source file. I hope it helps you.
