### ISSUE TITLE
Updated BOM and pick and place file for PCB Assembly

### ISSUE THREAD

**Issue by pushpinderv** [CNflysky/TC358870#4]
Please add updated BOM and pick and place file for contributors to be able to order a pre-assembled pcb from jlcpcb.
zengcym's repository seems to have two versions of the board, v1 and v2, and it is not clear which BOM file is relevant.

Could you share the BOM and pick and place file you used to order your sample?

**Comment by CNflysky** [comment]
PCB file uploaded so I'm closing it.
