### ISSUE TITLE
Screen compatibility?

### ISSUE THREAD

**Issue by ashrond** [CNflysky/TC358870#5]
Support for 10.1" screen was removed, I suppose this is actually just the 50 pin version?
I am looking for a bridge circuit that I can use to drive a 10.1", 34pin screen:
https://www.hy-line-group.com/products/hcc/displays/auo/b101uan01.7.pdf

**Comment by CNflysky** [comment]
be advised，every MIPI DSI panel requires a "initial code"，which is most panel specified and **NOT** compatible with other panels even if they shares same driver IC. So it is almost **IMPOSSIBLE** to develop such a "universal driver" for MIPI DSI panels. you should design your own adapter board and write panel driver by your own.

**Comment by ashrond** [comment]
i appreciate the response, thank you for the information.

**Comment by CNflysky** [comment]
stale
